language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - "pip install flake8 coveralls"
before_script:
  - "flake8 boggle"
# command to run tests
script:
  - "coverage run -m unittest discover"
after_success:
  - "coveralls"
