language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
before_install: "pip install codecov"
install:
  - "pip install flake8"
before_script: "flake8 *.py"
# command to run tests
script: python -m unittest boggle
after_success: "codecov"
