language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - "pip install flake8"
  - "pip install coveralls"
  - "pip install pyflakes"
before_script:
  - "flake8 ."
  - "pyflakes ."
script:
  - "coverage run -m unittest discover"
after_success:
  - "coveralls"
