language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - "pip install flake8"
  - "pip install coveralls"
before_script:
  - "flake8 ."
script:
  - "coverage run --source=boggle -m unittest discover"
after_success:
  - "coveralls"
cache:
  directories:
    - $HOME/.cache/pip
